### ISSUE TITLE
Add missing graphic modes

### ISSUE THREAD

**Issue by saurabhdaware** [saurabhdaware/cli-testing-library#2]
Check out the graphic modes list here - https://gist.github.com/fnky/458719343aabd01cfb17a3a4f7296797#colors--graphics-mode

We have to add support to tokenize them in the code

**Comment by judicaelandria** [comment]
what do you mean by tokenize them in the code?

**Comment by saurabhdaware** [comment]
So we currently turn ASCII escape codes into readable tokens like `[BOLD_START]` `[RED_START]` etc. You can check out this example - https://stackblitz.com/edit/node-kfod5b?file=examples%2Fgraphic-hello-world%2Fgraphic-hello-world.test.js

We have to add support for the rest of the graphic tokens like these

**Comment by saurabhdaware** [comment]
Resolved in [v0.1.0](https://github.com/saurabhdaware/cli-testing-library/releases/tag/v0.1.0)
